export const lesson = {
  number: "1.1",
  title: "You have Already Experienced Change Management — You Just Didn’t Call It That",
  tabs: [
    "Think about change",
    "You have experienced it",
    "The shift",
    "The mindset",
  ],
  opening: {
    heading: "Think about the last time something changed in your life…",
    subheading: "Something outside your normal routine…",
    examples: [
      "Maybe a new app you had to start using",
      "A new school system",
      "A new workplace process",
      "A new team, role, or expectation",
    ],
    sequence: [
      "At first, it felt small.",
      "Just a “simple update.”",
      "But then…",
      "You hesitated.",
      "You asked questions.",
      "You compared it to the old way.",
      "You maybe even resisted it—quietly.",
      "And slowly, over time, you adjusted.",
    ],
    conclusion: [
      "What you experienced in that moment wasn’t just change.",
      "It was change management.",
    ],
  },
  experience: {
    heading: "You have Already Experienced Change Management — You Just Didn’t Call It That",
    intro: "Every change you’ve lived through had the same invisible elements:",
    stages: [
      { title: "Awareness", body: "Understanding what is changing" },
      { title: "Reaction", body: "Confusion, concern, or even resistance" },
      { title: "Adjustment", body: "Learning how to operate in the new reality" },
      { title: "Adoption", body: "Making the new way your normal" },
    ],
    bridge: [
      "Whether you realized it or not…",
      "You were going through a structured human transition.",
    ],
    question: [
      "So the real question is not: Will change happen?",
      "Because it always does.",
      "The real question is:",
      "How will people experience that change—and how will you support them through it?",
    ],
  },
  shift: {
    heading: "The Shift That Changes Everything",
    conventionalIntro: "Most people think change management is:",
    conventional: ["Communication", "Training", "Announcements"],
    deeperIntro: "But real change management is something deeper:",
    deeper: [
      "It is helping people move from uncertainty to confidence",
      "It is turning resistance into understanding",
      "It is making the new way easier than the old way",
    ],
    question: "What separates successful change from failed change?",
    answer: [
      "It’s not the quality of the solution.",
      "It’s the quality of the transition.",
    ],
    caseStudyIntro: "That’s why in the case study below:",
    caseStudy: [
      "Listening mattered more than enforcing",
      "Targeted support worked better than generic training",
      "Leadership clarity reduced fear",
      "Feedback loops rebuilt trust",
    ],
  },
  mindset: {
    heading: "The Most Important Mindset to Adopt",
    intro: "As you continue your CCMP journey, this is the mindset that will shape everything:",
    principles: [
      "Focus on adoption, not just implementation",
      "Diagnose people challenges, not just system issues",
      "Understand behavior, not just processes",
      "Enable progress, not just completion",
    ],
    conclusion: [
      "Because at the end of the day…",
      "Change initiatives do not fail because they were designed poorly.",
      "They fail because people were expected to adapt— without being supported.",
      "And when you understand that…",
      "You’re no longer just observing change.",
      "You are learning how to lead it.",
    ],
  },
};
